name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "moon"
  comment: "moon0"
  url: "https://sv1.romsforever.cc/N3DS/Pokemon%20Ultra%20Moon%20(USA)%20(En,Ja,Fr,De,Es,It,Zh,Ko).zip"
  file_name: "Moon.zip"
  piece_size: 2^21 
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
